# Generated by Django 3.0.7 on 2020-06-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('iniciales', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Descartes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(choices=[('MIV', 'Mezcla intra Venosa'), ('MNPE', 'Mezcla de Nutricion Parenteral Extemporanea')], default='MNPE', max_length=64)),
                ('Lote', models.CharField(max_length=64)),
                ('volumen', models.IntegerField()),
                ('guia', models.CharField(blank=True, max_length=64)),
                ('filtro', models.CharField(blank=True, max_length=64)),
                ('observaciones', models.CharField(blank=True, max_length=64)),
                ('borrado', models.BooleanField(default=False)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descartes.Motivo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descartes.Tecnico')),
            ],
        ),
    ]
