# Generated by Django 3.0.7 on 2020-06-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descartes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(max_length=64)),
                ('filtro', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='descartes',
            old_name='Lote',
            new_name='lote',
        ),
        migrations.AddField(
            model_name='descartes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
