# Generated by Django 3.0.7 on 2020-06-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descartes', '0002_auto_20200611_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='guia',
            name='filtro',
        ),
        migrations.AlterField(
            model_name='descartes',
            name='guia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='descartes.Guia'),
        ),
        migrations.AlterField(
            model_name='descartes',
            name='filtro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='descartes.Filtro'),
        ),
    ]
