# Generated by Django 3.0.7 on 2020-06-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descartes', '0003_auto_20200611_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descartes',
            name='filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='descartes.Filtro'),
        ),
        migrations.AlterField(
            model_name='descartes',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='descartes.Guia'),
        ),
        migrations.AlterField(
            model_name='descartes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
