# Generated by Django 3.0.7 on 2020-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descartes', '0004_auto_20200611_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='iniciales',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
