# Generated by Django 3.0.7 on 2020-06-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descartes', '0005_auto_20200611_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='descartes',
            name='linea',
            field=models.CharField(choices=[('Blanca', 'Blanca'), ('Verde', 'Verde'), ('Amarilla', 'Amarilla'), ('Celeste', 'Celeste'), ('Rosa', 'Rosa'), ('N/A', 'No aplica')], default='N/A', max_length=64),
        ),
        migrations.AlterField(
            model_name='descartes',
            name='filtro',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='descartes.Filtro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descartes',
            name='guia',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='descartes.Guia'),
            preserve_default=False,
        ),
    ]
