# Generated by Django 3.0.7 on 2020-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descartes', '0006_auto_20200611_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descartes',
            name='linea',
            field=models.CharField(choices=[('B', 'Blanca'), ('V', 'Verde'), ('A', 'Amarilla'), ('C', 'Celeste'), ('R', 'Rosa'), ('N/A', 'No aplica')], default='N/A', max_length=64),
        ),
    ]
